env:
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
  - tsconfig.json
rules:
  quote-props:
  - error
  - consistent
  "@typescript-eslint/indent":
  - error
  - 4
  "@typescript-eslint/quotes":
  - error
  - double
  "@typescript-eslint/semi":
  - error
  - always
  "@typescript-eslint/space-before-function-paren":
  - warn
  - never
  "@typescript-eslint/consistent-type-definitions":
  - error
  - type
  "@typescript-eslint/restrict-template-expressions": warn
  "@typescript-eslint/no-non-null-asserted-optional-chain": warn
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-floating-promises": warn